languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Enutie"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Enutie"
  image = "img/author.jpg"
  headline = "I will continue to fail and that is progress."
  bio = "Web Developer - Learning Game Development, Drawing, Music and Writing"
  links = [
    { email = "mailto:enutie@gmail.com" },
    { github = "https://github.com/enutie" },
    { instagram = "https://instagram.com/modp" },
    { linkedin = "https://linkedin.com/in/modp" },
    { youtube = "https://www.youtube.com/@Enutie" },
   ]
