baseURL = "https://blog.enutie.com/"



# Change the default theme to be use when building the site with Hugo

theme = "LoveIt"



# website title

title = "Enuties Blog"



# language code ["en", "zh-CN", "fr", "pl", ...]

languageCode = "en"

# language name ["English", "简体中文", "Français", "Polski", ...]

languageName = "English"

enableGitInfo = true

enableEmoji = true

[pagination]
    disableAliases = false
    pagerSize = 10
    path = "page"



# Menu config

[menu]

  [[menu.main]]

    weight = 1

    identifier = "posts"

    # you can add extra information before the name (HTML format is supported), such as icons

    pre = ""

    # you can add extra information after the name (HTML format is supported), such as icons

    post = ""

    name = "Posts"

    url = "/posts/"

    # title will be shown when you hover on this menu link

    title = ""

  [[menu.main]]

    weight = 2

    identifier = "tags"

    pre = ""

    post = ""

    name = "Tags"

    url = "/tags/"

    title = ""

  [[menu.main]]

    weight = 3

    identifier = "categories"

    pre = ""

    post = ""

    name = "Categories"

    url = "/categories/"

    title = ""

[params]
    defaultTheme = "auto"
    gitRepo = "https://github.com/Enutie/Blog" 
    description = "My creative outlet"
    images = ["/images/author.jpg"]

[params.author]
    name = "Morten Dahl Pedersen"
    email = "Enutie@gmail.com"
    link = "https://github.com/Enutie"

[params.header.title]
    name = "Enutie's Blog"

[params.footer]
    enable = true
    hugo = false

[params.section]
    paginate = 20
    rss = 10

[params.app]
    title = "Enutie's Blog"


[params.home]
    rss = 10
    [params.home.profile]
        enable = true
        avatarUrl = "/images/author.jpg"
        title = "Enutie"
        subtitle = "No need to read this, its just for me."
        social = true
    [params.home.posts]
        enable = true
        paginate = 5

[params.social]
    GitHub = "/Enutie"
    Linkedin = "modp"
    Instagram = "enutiedraws"
    Email = "enutie@gmail.com"
    RSS = true

[params.page]

    [params.page.code]
        copy = true
        maxShownLines = 20

    [params.page.toc]
        enable = true
        auto = true


[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "MarkDown"]
    section = ["HTML", "RSS"]
    taxonomy = ["HTML", "RSS"]


# Markup related configuration in Hugo

[markup]

  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)

  [markup.highlight]

    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)

    noClasses = false
    lineNos = true
    guessSyntax = true