baseURL = 'https://blog.enutie.com'
languageCode = 'en'
title = 'Enutie Blog'
theme = 'ananke'

[params]
  author = 'Enutie'
  description = 'My creative journey - art, code, and games'
  
[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 10